### PR TITLE
Fix test_jobsub

### PR DESCRIPTION
**Pull request by hgreenlee**

### CODE REVIEW

**Comment by hgreenlee** [comment]
reject

**Comment by gartung** [comment]
You can enter close as a comment to automatically close this.

**Comment by greenc-FNAL** [comment]
@gartung I'm confused by this workflow: it was rejected and then merged?

**Comment by gartung** [comment]
I wondered about that too. It may be because the merge hgreenlee:develop on another pull request. I don't think the Greeting workflow merged it but I will look into it.

**Comment by gartung** [comment]
Or there were common commits on both pull requests?

**Comment by gartung** [comment]
Although I have seen the workflows run once a pull request is merged to the primary branch. If you look at the output it takes no action is taken.

**Comment by hgreenlee** [comment]
Hello,

The first time I put in the latest merge to larbatch, it was auto-rejected 
because of trailing whitespace.  The error message instructed me to create 
a new merge branch.

Herb

**Comment by gartung** [comment]
You need to merge from upstream/develop before pushing.

**Comment by gartung** [comment]
The -code-checks message is not a rejection. The code-checks message gives directions on how to remove the trailing whitespace. Once that is done you make a commit with the changes and push the branch to your fork. The pull request is then retested.

**Comment by gartung** [comment]
On a side note I will remove code-checks from larbatch and larutils.

**Pull request merged**
